name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  docker-test:
    strategy:
      matrix:
        smalltalk: [ Pharo64-13, Pharo64-12 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image with Smalltalk
        run: |
          docker build \
            --build-arg SMALLTALK_VERSION=${{ matrix.smalltalk }} \
            -t my-ollama-image:${{ matrix.smalltalk }} .

      - name: Run tests inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            my-ollama-image:${{ matrix.smalltalk }} \
            /usr/local/bin/pharo /var/pharo/images/default/Pharo.image smalltalkci -s ${{ matrix.smalltalk }}
