name: Sync Wiki to Pharo Wiki Repository

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  sync-wiki:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone Pharo Wiki Repository
        env:
          WIKI_REPO: https://github.com/omarabedelkader/ChatPharo.wiki.git
        run: |
          git clone $WIKI_REPO wiki-repo

      - name: Copy wiki file to wiki repository
        run: |
          cp doc/ChatPharo-Wiki.md wiki-repo/ChatPharo-Wiki.md

      - name: Commit and push changes
        run: |
          cd wiki-repo
          git add ChatPharo-Wiki.md
          git commit -m "Update wiki from project repo [automated]" || echo "No changes to commit"
          git push
